# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\x1e\n\x0bgRPCRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x1c\n\tgRPCReply\x12\x0f\n\x07message\x18\x01 \x01(\t2D\n\x07Greeter\x12\x39\n\x0bgRPCCmdLine\x12\x14.example.gRPCRequest\x1a\x12.example.gRPCReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRPCREQUEST']._serialized_start=26
  _globals['_GRPCREQUEST']._serialized_end=56
  _globals['_GRPCREPLY']._serialized_start=58
  _globals['_GRPCREPLY']._serialized_end=86
  _globals['_GREETER']._serialized_start=88
  _globals['_GREETER']._serialized_end=156
# @@protoc_insertion_point(module_scope)
